import Head from "next/head";
import CustomersList from "@/components/pages/customers/CustomersList";
import MainLayout from "@/components/common/layouts/MainLayout";
import OrderDetaill from "@/components/pages/orders/ordersData/OrderDetail";
import styles from "@/styles/Home.module.css";
export default function OrderDetail() {
  return (
    <>
      <Head>
        <title>Order Detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
       <OrderDetaill/>
      </div>
    </>
  );
}

OrderDetail.getLayout = (pageProps) => (
  <MainLayout>
    <OrderDetail {...pageProps} />
  </MainLayout>
);