import Head from "next/head";
import CustomersList from "@/components/pages/customers/CustomersList";
import MainLayout from "@/components/common/layouts/MainLayout";
import Card from "@/components/pages/food/Card";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Grid } from "@mui/system";

export default function FoodsList() {
  return (
    <>
      <Head>
        <title>Foods List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Grid container spacing={2}>
          <Grid size={{ sm: 6, md: 6 }}>
            <h1>Foods</h1>
            <p style={{ color: "gray" }}>
              Here is your menus summary with graph view
            </p>
          </Grid>
          <Grid container spacing={2} size={{ sm: 6, md: 6 }}>
            <Grid size={{ sm: 4, md: 4 }}>
             <img style={{ alignItems: "center" }} src="search (2).png"/>
              <input
                style={{
                  width: 291,
                  height: 68,
                  top: 141,
                  left: 994,
                  borderRadius: 15,
                  border: 0,
                }}
                type="text"
                placeholder="Search here"
              />
            </Grid>
            <Grid size={{ sm: 8, md: 8 }}>
              <button  style={{border: "1px rgb(205, 202, 202) solid",padding:"12px",borderRadius:"5px", background: "#FFFFFF",}} >  < img src="./chiziq.png" alt="" /></button>
              <button    style={{border: "1px rgb(205, 202, 202) solid",borderRadius:"5px", background: "#FFFFFF",}} >  <img src="./Layer 56.png" alt="" /></button>
              <button style={{border: 0 , background:"#FFFFFF"}} onClick={() => window.location.href = 'http://localhost:3000/foods/new'}>
                 <img src="./icGridview.png" alt="Add" />
              </button>
            </Grid>
          </Grid>
        </Grid>
          <Card />

        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-around",
            marginTop:"20px"
          }}
        >
          <h1>Menu Comparison</h1>
          <div style={{ display: "flex" }}>
            <p style={{ marginRight: 10 }}>Chart</p>
            <input type="checkbox" />
          </div>
          <div style={{ display: "flex" }}>
            <p style={{ marginRight: 10 }}>Show Value</p>
            <input type="checkbox" />
          </div>
          <img src="./3nuqta.png" alt="" />
        </div>
        <div style={{ display: "flex", justifyContent: "space-around" }}>
          <img src="./stats2.png" alt="" />
          <img src="./stats3.png" alt="" />
          <img src="./stats4.png" alt="" />
        </div>
      </div>
    </>
  );
}

FoodsList.getLayout = (pageProps) => (
  <MainLayout>
    <FoodsList {...pageProps} />
  </MainLayout>
);
