import { orderListData as d } from "@/Data";
import MainLayout from "@/components/common/layouts/MainLayout";
import styles from "@/styles/orderDetail.module.css";
import Image from "next/image";
import Head from "next/head";
import { styled } from "@mui/material/styles";
import Box from "@mui/material/Box";
import Paper from "@mui/material/Paper";
import Grid from "@mui/material/Grid";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Link from "next/link";

function OrderDetail() {
  const router = useRouter();
  const [currentOrder, setCurrentOrder] = useState(null);
  const [tableItems, setTableItems] = useState([]);

  useEffect(() => {
    if (router.query.id) {
      const orderItem = d.find((o) => o.id === router.query.id);
      if (orderItem) {
        setCurrentOrder(orderItem);
        setTableItems(orderItem.items);
      }
    }
  }, [router]);

  const handleDelete = (id) => {
    setTableItems((items) => items.filter((item) => item.id !== id));
  };

  return (
    <>
      <Head>
        <title>
          {currentOrder
            ? "Order Detail: " + currentOrder.id
            : "Tovar not found"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {currentOrder ? (
        <div style={{ width: "100%", maxWidth: "1468px", margin: "0 auto" }}>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              marginBottom: "48px",
            }}
          >
            <div>
              <h1 style={{ fontSize: "32px" }}>
                {`Order ID #${currentOrder.id}`}
              </h1>
              <p style={{ fontSize: "18px" }}>
                <Link href="/orders" style={{ color: "#00B074" }}>
                  Orders /
                </Link>{" "}
                Order Detail
              </p>
            </div>
            <div style={{ display: "flex" }}>
              <button
                style={{
                  padding: "18px 65px",
                  backgroundColor: "unset",
                  border: "1px solid #ff5b5b",
                  borderRadius: "12px",
                  cursor: "pointer",
                }}
              >
                Cancel Order
              </button>
              <select
                style={{
                  padding: "18px 65px",
                  backgroundColor: "#00b074",
                  borderRadius: "12px",
                  border: "1px solid #00b074",
                  color: "white",
                  outlineStyle: "none",
                  marginLeft: "40px",
                  cursor: "pointer",
                }}
              >
                <option>On Delivery</option>
              </select>
            </div>
          </div>

          <Grid container spacing={2} style={{ display: "flex" }}>
            <Grid
              size={{ md: 4, lg: 6 }}
              style={{ width: "339px", borderRadius: "16px" }}
            >
              <div
                style={{
                  padding: "30px",
                  backgroundColor: "white",
                  borderRadius: "16px",
                }}
              >
                <div
                  style={{
                    width: "160px",
                    height: "160px",
                    backgroundColor: "gray",
                    borderRadius: "50%",
                    margin: "30px auto",
                  }}
                ></div>
                <p
                  style={{
                    fontSize: "18px",
                    color: "#3e4954",
                    textAlign: "center",
                  }}
                >
                  {currentOrder.customer.name}
                </p>
                <div
                  style={{
                    backgroundColor: "#00b07426",
                    color: "#00b074",
                    borderRadius: "6px",
                    margin: "10px auto",
                    width: "93px",
                    padding: "8px",
                    textAlign: "center",
                    fontSize: "12px",
                  }}
                >
                  Customer
                </div>
                <div
                  style={{
                    width: "100%",
                    borderRadius: "16px",
                    backgroundColor: "#5e6c93",
                  }}
                >
                  <h2
                    style={{
                      fontSize: "24px",
                      color: "white",
                      padding: "30px 0px 0px 30px",
                    }}
                  >
                    Note Order
                  </h2>
                  <p
                    style={{
                      fontSize: "14px",
                      color: "white",
                      lineHeight: "26px",
                      padding: "20px 0px 40px 30px",
                      fontWeight: "400",
                      width: "340px",
                    }}
                  >
                    {currentOrder.customer.noteOrder}
                  </p>
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      backgroundColor: "#2d9cdb",
                      borderRadius: "16px",
                    }}
                  >
                    <div
                      style={{
                        width: "49px",
                        height: "49px",
                        backgroundColor: "white",
                        borderRadius: "50%",
                        margin: "30px 30px",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                      }}
                    >
                      <Image
                        src="/shipping.png"
                        alt="truck"
                        width={28}
                        height={28}
                      />
                    </div>
                    <p style={{ color: "white", width: "157px" }}>
                      {currentOrder.customer.manzil}
                    </p>
                  </div>
                </div>

                <div style={{ marginTop: "30px" }}>
                  <h2 style={{ fontSize: "24px", color: "white" }}>History</h2>
                  {[1, 2, 3].map((_, i) => (
                    <div
                      key={i}
                      style={{
                        display: "flex",
                        alignItems: "center",
                        marginTop: "15px",
                      }}
                    >
                      <Image
                        style={{ backgroundColor: "unset" }}
                        src={"/dot.png"}
                        alt="dot"
                        width={26}
                        height={26}
                      />
                      <div style={{ marginLeft: "50px" }}>
                        <h3 style={{ fontSize: "18px", color: "white" }}>
                          {currentOrder.history.name}
                        </h3>
                        <p style={{ fontSize: "14px", color: "white" }}>
                          {currentOrder.history.sana}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </Grid>

            <Grid size={{ md: 8, lg: 6 }} style={{ width: "1089px" }}>
              <div
                style={{
                  backgroundColor: "white",
                  border: "1px solid rgb(218, 218, 218)",
                  borderRadius: "16px",
                  marginBottom: "40px",
                }}
              >
                <Table items={tableItems} handleDelete={handleDelete} />
              </div>
              <div
                style={{
                  backgroundColor: "white",
                  border: "1px solid rgb(241, 241, 241)",
                  borderRadius: "16px",
                }}
              >
                <div
                  style={{
                    backgroundColor: "gray",
                    borderRadius: "16px",
                    margin: "30px 30px",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                >
                  <Image src="" alt="map" width={1030} height={350} />
                </div>
                <p
                  style={{
                    fontSize: "24px",
                    color: "#464255",
                    padding: "0px 0px 10px 30px",
                  }}
                >
                  Delivery by
                </p>
                <Grid
                  container
                  spacing={3}
                  style={{ display: "flex", justifyContent: "space-between" }}
                >
                  <Grid size={6} style={{ display: "flex" }}>
                    <div
                      style={{
                        width: "68px",
                        height: "68px",
                        borderRadius: "50%",
                        backgroundColor: "gray",
                        marginRight: "40px",
                        marginLeft: "10px",
                      }}
                    ></div>
                    <div style={{ padding: "10px", color: "#3e4954" }}>
                      <p
                        style={{
                          padding: "7px 0px",
                          fontSize: "24px",
                          color: "#3e4954",
                        }}
                      >
                        {currentOrder.deliveredBy.name}
                      </p>
                      <p style={{ fontSize: "14px", color: "#969ba0" }}>
                        ID - {currentOrder.deliveredBy.id}
                      </p>
                    </div>
                  </Grid>
                  <div style={{ display: "flex" }}>
                    <Button
                      size={6}
                      title={"Telephone"}
                      phoneNumber={currentOrder.deliveredBy.phone}
                      src={"/phoneIcon.png"}
                    />
                    <Button
                      size={6}
                      title={"Delivery Time"}
                      time={currentOrder.deliveredBy.time}
                      src={"/shipping.png"}
                    />
                  </div>
                </Grid>
              </div>
            </Grid>
          </Grid>
        </div>
      ) : (
        <div>
          <p>Tovar not found</p>
        </div>
      )}
    </>
  );
}

export default OrderDetail;

function Button(props) {
  const { title, phoneNumber, src, time } = props;
  return (
    <button>
      <div>
        <Image
          style={{ backgroundColor: "unset" }}
          src={src}
          alt="phone"
          width={26}
          height={26}
        />
      </div>
      <div className={styles["numDrAndTime"]}>
        <p>{title}</p>
        <p>
          {phoneNumber} {time}
        </p>
      </div>
    </button>
  );
}

function Table({ items, handleDelete }) {
  const columns = [
    {
      id: "1",
      name: "Item",
    },
    {
      id: "2",
      name: "Qty",
    },
    {
      id: "3",
      name: "Price",
    },
    {
      id: "4",
      name: "Total Price",
    },
    {
      id: "5",
      name: "",
    },
  ];

  return (
    <table className={styles["detailtable"]}>
      <thead>
        <tr className={styles["tr"]}>
          {columns.map((col) => (
            <th key={col.id} className={styles["userth"]}>
              {col.name}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {items.map((item) => (
          <TableRow key={item.id} item={item} handleDelete={handleDelete} />
        ))}
      </tbody>
    </table>
  );
}

function TableRow(props) {
  const { item, handleDelete } = props;
  return (
    <tr className={styles["usertr"]}>
      <td className={styles["usertd"]}>{item.name}</td>
      <td className={styles["usertd"]}>{item.qty}</td>
      <td className={styles["usertd"]}>{item.price}</td>
      <td className={styles["usertd"]}>{item.price * item.qty}</td>
      <td className={styles["usertd"]}>
        <button
          onClick={() => handleDelete(item.id)}
          style={{
            borderRadius: "50%",
            width: "20px",
            height: "20px",
            border: "1px solid red",
            color: "red",
            background: "unset",
            cursor: "pointer",
          }}
        >
          x
        </button>
      </td>
    </tr>
  );
}

OrderDetail.getLayout = (pageProps) => (
  <MainLayout>
    <OrderDetail {...pageProps} />
  </MainLayout>
);
