import Head from "next/head";
import CustomersList from "@/components/pages/customers/CustomersList";
import MainLayout from "@/components/common/layouts/MainLayout";
import styles from "@/styles/Home.module.css";

export default function FoodsId() {
  return (
    <>
      <Head>
        <title>Foods Id</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      Foods Id
      </div>
    </>
  );
}

FoodsId.getLayout = (pageProps) => (
  <MainLayout>
    <FoodsId {...pageProps} />
  </MainLayout>
);
